### ISSUE TITLE
Image Thumbnail not being updated while re-capturing

### ISSUE THREAD

**Issue by khyativyasargus** [google-research/CVD-paper-mobile-camera-example#57]
While Re-capturing Image, Thumbnail is not being updated right away, but if we go previous or next and come back to the same item, it does! 

@MJ1998

**Comment by MJ1998** [comment]
This is due to the file location being the same, the answer component does not change and hence the UI does not update the thumbnail!

Current solution to this would be to remove the previous answer and add a new one. These APIs are available in the current master branch of datacapture library which will be available in the next release!
